services:
  wordpress:
    image: wordpress:php8.2
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html:cached
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: bsahlen
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./backups:/backups
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bsahlen
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db

volumes:
  db_data:
